### ISSUE TITLE
port number value limited?

### ISSUE THREAD

**Issue by jakenl** [MappaM/HTTPLocalePlugin#1]
thanks for your plugin. However there is a little issue with it. I use a very high port number to connect, 30808. This is not working. Port number 8080 works good. The high port number is no problem in the browser and therefore the issue seems to be within your plugin.

**Comment by tbarbette** [comment]
Hi,

It always use the destination port 80 (or 443 https) as it is standard. The source port is randomly choosen as with all HTTP Client. I use the default parameters. Can you describe more your problem?

Tom

**Comment by jakenl** [comment]
Hi Tom, I want to send the following command to my Domoticz system:
http://user:password@externalIP:30808/json.htm?type=command&param=switchlight&idx=48&switchcmd=On

It is the 30808 that is not accepted by your plugin, although via the browser it works fine. When I use your plugin in the internal network, I need to use port 8080 instead of 30808 and then your plugin works fine as well.

Jacco

Tom Barbette notifications@github.com schreef op 29 november 2015 11:00:18 CET:

**Comment by tbarbette** [comment]
I checked and the request is sent on the port 30808 without any problem. The problem seems to be elsewhere. You can MP me with the exact url to call so I can try if you want. But I do nothing special with the port, it's all the standard android way...

**Comment by tbarbette** [comment]
I'll update my code to use the last android HTTP Api before that. Stay tuned.

**Comment by tbarbette** [comment]
Ok I sent the update on google play, it will roll out in a few hours. I tried to make a connection to a server on port 30800 and it worked ;)

**Comment by jakenl** [comment]
Thanks Tom for the effort you are putting into it. However it is still not working. When I trigger the event, only after a minute the'toast' message shows up saying that the call returned an error.

This is the link I use:
http://external-IP:32808/json.htm?type=command&param=switchlight&idx=48&switchcmd=Off
You can try it for testing, but please not every day. It would ruin my automation plans ;)

Merci beaucoup,

Jacco

Tom Barbette notifications@github.com schreef op 29 november 2015 18:40:29 CET:

**Comment by jakenl** [comment]
a 2nd reply: I did my previous tests with my cell phone browser. When I 
try it with my desktop pc, the http string returns an 401 not authorized 
message. Therefore probably something is wrong with the authentication 
part of the domotica program (since you don't need to login via the 
local network)

I will come back to you as soon as logging in through the browser works 
OK for me.

**Comment by tbarbette** [comment]
Ok. In the meantime I noted your URL, remove it from your message or some bot will call it ^^

PS : French :p

**Comment by tbarbette** [comment]
Any news?

**Comment by jakenl** [comment]
No, except that I have seen a similar issue from another Domoticz user.

Tom Barbette notifications@github.com schreef op 11 december 2015 13:16:26 CET:
