### ISSUE TITLE
Toast message

### ISSUE THREAD

**Issue by 10RUPTiV** [MappaM/HTTPLocalePlugin#2]
Hi Tom,

I'm looking to use this plugin with locale as the other issue already opened.  I can call my URL without a problem in any browser either from Android or Windows.

But inside your plugin, it give me a toast message!

My URL looks like 

http://user:password@MYDOMAIN/data_request?id=action&output_format=xml&DeviceNum=51&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0

Maybe it's because of the return I'm having from my URL.

<u:SetTargetResponse xmlns:u="urn:upnp-org:serviceId:SwitchPower1">
<OK>OK</OK>
</u:SetTargetResponse>

**Comment by tbarbette** [comment]
Hey !
What is the toast message?
